#!/bin/sh

case "$1" in
	start)
		# The app is started by init scripts, so set locale here.
		export LANG=C
		export LC_ALL=C
		export PYTHONUTF8=1
		export PYTHONIOENCODING=utf-8
		/usr/bin/python3 /usr/bin/chochodile.py </dev/console >/dev/console 2>&1 &
		;;
esac

exit 0
